#!/bin/bash

# What are global and regional app usage trends?
# Lockbox table (by app, by user logs). It is biased to those who opted-in,
# ~60% and skewed to Android. play_apps_consumer_readers.audi_lockbox.latest
# (no country) Matt K.
# To add countries in mainline, on GAIA_id: finsky.usertags.3daysago
# Time spent (trends) in walled gardens (competitors vs ours like YT),
# vs. other apps (by vertical, sub-vertical).
# The same data sources: https://cs.corp.google.com/piper///depot/google3/experimental/users/lavans/projects/carrier_stats/engagement.sql

SET accounting_group analytics-internal-processing-dev;
SET min_completion_ratio 1;
SET io_timeout 2400;
SET nest_join_schema true;
SET runtime_name dremel;
SET materialize_overwrite true;
SET materialize_owner_group analytics-internal-processing-dev;
SET nest_join_schema False;
SET dat_policy dremel;

MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/all_apps_browsers/data' AS
SELECT
  STRFTIME_USEC(TIME_USEC_TO_DAY(events.timestamp_usec),'%Y%m%d') AS date,
  IF(events.lockbox_task_info.base_activity_package_name IN
    (
    'com.android.browser', 'com.android.chrome',
    'com.htc.sense.browser', 'com.opera.browser', 'com.opera.max.oem',
    'com.opera.mini.android', 'com.opera.mini.native',
    'com.sec.android.app.sbrowser', 'com.uc.browser.en',
    'com.UCMobile.intl', 'com.yandex.browser', 'org.mozilla.firefox'
    ), 'web','app') AS traffic,
  ROUND(SUM(events.duration_msec/60000)) AS mins
FROM FLATTEN(play_apps_consumer_readers.audi_lockbox.2017, events)
WHERE NOT
  (
  # Exluding launchers
  events.lockbox_task_info.base_activity_package_name CONTAINS
    'launcher'
  # Excluding messangers, phones
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.sonyericsson')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.sec.android')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.samsung')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.motorola')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.lenovo')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.cisco')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.verizon.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.miui.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.imo.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.htc.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.bbm')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.lge.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.asus.')
  )
GROUP@500 BY 1,2;

MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/wg_aggregated/data' AS
SELECT
  STRFTIME_USEC(TIME_USEC_TO_DAY(events.timestamp_usec),'%Y%m%d') AS date,
  ROUND(SUM(events.duration_msec/60000)) AS mins,
FROM FLATTEN(play_apps_consumer_readers.audi_lockbox.2017, events)
WHERE events.lockbox_task_info.base_activity_package_name IN
  (
  # Walled gardens.
    'com.google.android.youtube', 'com.google.android.apps.youtube.kids',
    'com.google.android.apps.youtube.music',
    'com.linkedin.android',
    'com.twitter.android',
    'com.pinterest',
    'com.facebook.katana', 'com.facebook.orca', 'com.facebook.lite',
    'com.whatsapp',
    'com.instagram.android',
    'com.vkontakte.android', 'ru.ok.android',
    'com.kakao.talk',
    'jp.naver.line.android',
    'com.snapchat.android',
    'com.viber.voip',
    'org.telegram.messenger',
    'com.tencent.mm',
    'com.jio.join',
    'com.skype.raider'
   )
GROUP@500 BY 1;

MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/wg_split/data' AS
SELECT
  events.lockbox_task_info.base_activity_package_name AS app,
  ROUND(SUM(events.duration_msec/60000)) AS mins
FROM FLATTEN(play_apps_consumer_readers.audi_lockbox.2017, events)
WHERE
  events.lockbox_task_info.base_activity_package_name  IN
  (
    # Walled gardens.
    'com.google.android.youtube', 'com.google.android.apps.youtube.kids',
    'com.google.android.apps.youtube.music',
    'com.linkedin.android',
    'com.twitter.android',
    'com.pinterest',
    'com.facebook.katana', 'com.facebook.orca', 'com.facebook.lite',
    'com.whatsapp',
    'com.instagram.android',
    'com.vkontakte.android', 'ru.ok.android',
    'com.kakao.talk',
    'jp.naver.line.android',
    'com.snapchat.android',
    'com.viber.voip',
    'org.telegram.messenger',
    'com.tencent.mm',
    'com.jio.join',
    'com.skype.raider'
   )
GROUP@500 BY 1;

MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/time_by_apps/data' AS
SELECT
  events.lockbox_task_info.base_activity_package_name AS app,
  ROUND(SUM(events.duration_msec/60000)) AS mins
FROM FLATTEN(play_apps_consumer_readers.audi_lockbox.2017, events)
WHERE NOT
  (
  # Exluding launchers
  events.lockbox_task_info.base_activity_package_name CONTAINS
    'launcher'
  # Excluding messangers, phones
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.sonyericsson')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.sec.android')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.samsung')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.motorola')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.lenovo')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.cisco')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.verizon.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.miui.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.imo.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.htc.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.bbm')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.lge.')
  OR events.lockbox_task_info.base_activity_package_name CONTAINS
      ('com.asus.')
  )
GROUP@500 BY 1;

MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/apps_categories/data' AS
SELECT
  package_name,
  CASE
    WHEN category IN (30, 13, 8, 18, 35) THEN 'books_libraries'
    WHEN category IN (5, 15, 59) THEN 'socail_communications'
    WHEN category IN (6, 60) THEN 'entertainment'
    WHEN category IN (19,22,23) THEN 'medical'
    WHEN category IN (62,9,63,20,58,56) THEN 'lifestyle_sport'
    WHEN category IN (11,27) THEN 'news'
    WHEN category IN (17,33) THEN 'travel'
    WHEN category IN (66, 32, 12, 21, 16,28) THEN 'utilities'
    WHEN category IN (24, 10, 25, 65, 26) THEN 'media_and_multimedia'
    WHEN category IN (38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
      53, 54, 55) THEN 'games'
    WHEN category = 57 THEN 'auto_and_vehicles'
    WHEN category = 29 THEN 'business'
    WHEN category = 31 THEN 'education'
    WHEN category = 7 THEN  'finance'
    WHEN category = 61 THEN 'food_and_drink'
    WHEN category = 14 THEN 'shopping'
  ELSE 'Other'
  END AS category_name
FROM play_analytics.apps_data.latest
GROUP@50 BY 1,2;

DEFINE TABLE time_by_apps /cns/ig-d/home/aredakov/apps_usage_stats/time_by_apps/data*;
DEFINE TABLE apps_categories /cns/ig-d/home/aredakov/apps_usage_stats/apps_categories/data*;
MATERIALIZE '/cns/ig-d/home/aredakov/apps_usage_stats/time_by_categories/data' AS
SELECT
  category_name,
  SUM(mins) AS mins
FROM time_by_apps a
LEFT JOIN@50 apps_categories b
ON app = package_name
GROUP@50 BY 1;

# Charts in R.
library(ginstall)
library(gfile)
library(namespacefs)
library(rglib)
library(cfs)
library(dremel)
library(gbm)
library(Hmisc)
library(ggplot2)
library(lubridate)
InitGoogle()
options("scipen"=100, "digits"=6)

myConn <- DremelConnect()
DremelSetMinCompletionRatio(myConn, 1.0)
DremelSetAccountingGroup(myConn,'urchin-processing-qa')
DremelSetMaterializeOwnerGroup(myConn, 'materialize-a-dremel')
DremelSetMaterializeOverwrite(myConn, TRUE)
DremelSetIOTimeout(myConn, 7200)
DremelSetEndUserCreds(myConn, GetEndUserCredsProto())

# All web/app usage.
DremelAddTableDef('all_apps_browsers', '/cns/ig-d/home/aredakov/apps_usage_stats/all_apps_browsers/data*',
  myConn, verbose=FALSE)

al <- DremelExecuteQuery("
  SELECT *
  FROM all_apps_browsers
  WHERE mins > 100
;", myConn)

al$date <- ymd(al$date)
pd <- position_dodge(.1)
ggplot(data = al, aes(x = date, y = mins/1000000000)) +
geom_point(aes(colour = 'red', alpha = 0.1)) +
stat_smooth(position=pd, method="loess", fullrange=TRUE, size=1.2, span=.4) +
facet_grid(traffic~.,scales='free') +
theme_bw() +
theme(legend.position="none") +
theme(strip.text=element_text(size=11,face="bold")) +
theme(axis.text.x=element_text(size=11,face="bold", angle = 45, hjust = 1)) +
theme(axis.text.y=element_text(size=11,face="bold", color="gray26")) +
ylab("Minutes Spent in App, Billions") +
ggtitle("Time in App vs Web (All Apps),
Billions Minutes") +
theme(plot.title = element_text(lineheight=.8))+
xlab("")

# Walled gardens: Aggregated.
DremelAddTableDef('wg_aggregated', '/cns/ig-d/home/aredakov/apps_usage_stats/wg_aggregated/data*',
  myConn, verbose=FALSE)

wga <- DremelExecuteQuery("
  SELECT *
  FROM wg_aggregated
  WHERE mins > 100
;", myConn)

wga$date <- ymd(wga$date)
pd <- position_dodge(.1)
ggplot(data = wga, aes(x = date, y = mins/1000000000)) +
geom_point(aes(colour = 'red', alpha = 0.1)) +
stat_smooth(position=pd, method="loess", fullrange=TRUE, size=1.2, span=.4) +
theme_bw() +
theme(legend.position="none") +
theme(strip.text=element_text(size=11,face="bold")) +
theme(axis.text.x=element_text(size=11,face="bold", angle = 45, hjust = 1)) +
theme(axis.text.y=element_text(size=11,face="bold", color="gray26")) +
ylab("Minutes Spent in App, Billions") +
ggtitle("Time in App – Walled Gardens Aggregated,
Billions Minutes") +
theme(plot.title = element_text(lineheight=.8))+
xlab("")

# Walled gardens: Split.
DremelAddTableDef('wg_split', '/cns/ig-d/home/aredakov/apps_usage_stats/wg_split/data*',
  myConn, verbose=FALSE)

wg <- DremelExecuteQuery("
  SELECT
   CASE
    WHEN app CONTAINS ('facebook') THEN 'facebook'
    WHEN app CONTAINS ('youtube') THEN 'youtube'
    WHEN app CONTAINS ('instagram') THEN 'instagram'
    WHEN app CONTAINS ('snapchat') THEN 'snapchat'
    WHEN app CONTAINS ('linkedin') THEN 'linkedin'
    WHEN app CONTAINS ('twitter') THEN 'twitter'
    WHEN app CONTAINS ('kakao') THEN 'kakao'
    WHEN app CONTAINS ('line') THEN 'line'
    WHEN app CONTAINS ('whatsapp') THEN 'whatsapp'
    WHEN app CONTAINS ('vkontakte') THEN 'vkontakte'
    WHEN app CONTAINS ('ru.ok') THEN 'ru.ok'
    WHEN app CONTAINS ('pinterest') THEN 'pinterest'
    WHEN app CONTAINS ('com.snapchat.android') THEN 'snapchat'
    WHEN app CONTAINS ('com.viber.voip') THEN 'viber'
    WHEN app CONTAINS ('org.telegram.messenger') THEN 'telegram'
    WHEN app CONTAINS ('com.tencent.mm') THEN 'tencent.mm'
    WHEN app CONTAINS ('com.jio.join') THEN 'jio'
    WHEN app CONTAINS ('com.skype.raider') THEN 'skype'
  END AS app,
  SUM(mins) AS mins
  FROM wg_split
  GROUP@50 BY 1
;", myConn)

ggplot(data = wg, aes(x = reorder(app, mins), y =  mins/1000000000, fill=app)) +
geom_bar(stat="identity") +
coord_flip()  +
theme_bw() +
theme(legend.position="none") +
geom_text(aes(label=sprintf("%1.0fB", mins/1000000000)),
  size=4) +
theme(strip.text=element_text(size=11,face="bold")) +
theme(axis.text.x=element_text(size=11,face="bold", angle = 45, hjust = 1)) +
theme(axis.text.y=element_text(size=11,face="bold", color="gray26")) +
ylab("Billions Minutes") +
ggtitle("Time in App in Walled Gardens
Billions Minutes") +
theme(plot.title = element_text(lineheight=.8))+
xlab("")

# Time in app by category.
DremelAddTableDef('time_by_categories', '/cns/ig-d/home/aredakov/apps_usage_stats/time_by_categories/data*',
  myConn, verbose=FALSE)

tc <- DremelExecuteQuery("
  SELECT
    category_name,
    mins
  FROM time_by_categories
  WHERE category_name IS NOT NULL
;", myConn)

tc$category_name <- factor(tc$category_name,
  levels= c('Other', 'food_and_drink', 'auto_and_vehicles', 'business',
  'finance', 'travel', 'medical', 'education', 'shopping', 'books_libraries',
  'news', 'lifestyle_sport', 'entertainment', 'socail_communications',
  'media_and_multimedia', 'utilities', 'games'))

ggplot(data = tc, aes(x = category_name, y =  mins/1000000000)) +
geom_bar(stat="identity", fill = "lightblue1") +
coord_flip()  +
theme_bw() +
theme(legend.position="none") +
geom_text(aes(label=sprintf("%1.0fB", mins/1000000000)),
  size=3.5) +
theme(strip.text=element_text(size=11,face="bold")) +
theme(axis.text.x=element_text(size=11,face="bold", angle = 45, hjust = 1)) +
theme(axis.text.y=element_text(size=11,face="bold", color="gray26")) +
ylab("Billions Minutes") +
ggtitle("Time in App by Categories.
Billions Minutes") +
theme(plot.title = element_text(lineheight=.8))+
xlab("")
